const $=id=>document.getElementById(id);let audioCtx=null,gain=null,running=false,timer=null,nextTime=0,beat=0,tempo=80,meter=4,sub=1,wakeLock=null,deferredInstall=null;const stateKey='jackson-metronome-v1';const state=JSON.parse(localStorage.getItem(stateKey)||'{}');
function save(){localStorage.setItem(stateKey,JSON.stringify({tempo,meter,sub,sound:$('sound').value,volume:$('volume').value,accent:$('accentToggle').checked,vibrate:$('vibrateToggle').checked}))}
function restore(){tempo=state.tempo||80;meter=state.meter||4;sub=state.sub||1;$('tempoSlider').value=tempo;$('bpmValue').textContent=tempo;$('meter').value=meter;$('subdivision').value=sub;if(state.sound)$('sound').value=state.sound;if(state.volume!=null){$('volume').value=state.volume;$('volumeValue').textContent=state.volume+'%'}if(state.accent!=null)$('accentToggle').checked=state.accent;if(state.vibrate!=null)$('vibrateToggle').checked=state.vibrate}
function initAudio(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume()}
function clickSound(time,isAccent){const osc=audioCtx.createOscillator(),g=audioCtx.createGain();const sound=$('sound').value;osc.type=sound==='wood'?'triangle':'sine';osc.frequency.setValueAtTime(sound==='soft'?850:(isAccent?1550:1050),time);g.gain.setValueAtTime(0,time);g.gain.linearRampToValueAtTime((Number($('volume').value)/100)*(isAccent?.24:.16),time+.002);g.gain.exponentialRampToValueAtTime(.001,time+.045);osc.connect(g);g.connect(gain);osc.start(time);osc.stop(time+.05)}
function tick(){const interval=60/tempo/sub;while(nextTime<audioCtx.currentTime+.12){const pos=beat%meter;const isAccent=pos===0&&$('accentToggle').checked;clickSound(nextTime,isAccent);setTimeout(()=>visualBeat(pos,isAccent),Math.max(0,(nextTime-audioCtx.currentTime)*1000));nextTime+=interval;beat++;}timer=setTimeout(tick,25)}
function visualBeat(pos,accent){$('beatText').textContent=`第 ${pos+1} 拍`;const d=$('beatDot');d.classList.toggle('accent',accent);d.classList.add('pulse');setTimeout(()=>d.classList.remove('pulse'),90);if($('vibrateToggle').checked&&navigator.vibrate)navigator.vibrate(accent?18:8)}
function start(){initAudio();running=true;beat=0;nextTime=audioCtx.currentTime+.05;tick();$('startText').textContent='停止';$('startIcon').textContent='■';$('startBtn').style.background='#343840'}function stop(){running=false;clearTimeout(timer);$('startText').textContent='开始';$('startIcon').textContent='▶';$('startBtn').style.background='';$('beatText').textContent='第 1 拍';$('beatDot').classList.remove('pulse','accent')}
$('startBtn').onclick=()=>running?stop():start();$('tempoSlider').oninput=e=>{tempo=+e.target.value;$('bpmValue').textContent=tempo;save()};$('minus5').onclick=()=>setTempo(tempo-5);$('plus5').onclick=()=>setTempo(tempo+5);function setTempo(v){tempo=Math.max(30,Math.min(300,v));$('tempoSlider').value=tempo;$('bpmValue').textContent=tempo;save()}
$('tempoDisplay').onclick=()=>{$('bpmInput').value=tempo;$('bpmDialog').showModal();setTimeout(()=>$('bpmInput').select(),50)};$('bpmForm').onsubmit=e=>{e.preventDefault();setTempo(+$('bpmInput').value||80);$('bpmDialog').close()};$('meter').onchange=e=>{meter=+e.target.value;save()};$('subdivision').onchange=e=>{sub=+e.target.value;save()};$('sound').onchange=save;$('volume').oninput=e=>{$('volumeValue').textContent=e.target.value+'%';save()};$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('accentToggle').onchange=save;$('vibrateToggle').onchange=save;
let taps=[];$('tapBtn').onclick=()=>{const now=performance.now();taps=taps.filter(t=>now-t<2200);taps.push(now);if(taps.length>=2){const avg=(taps[taps.length-1]-taps[0])/(taps.length-1);setTempo(Math.round(60000/avg))}if(taps.length>=6)taps=taps.slice(-4)};
$('wakeBtn').onclick=async()=>{try{if('wakeLock'in navigator){if(wakeLock){await wakeLock.release();wakeLock=null;$('wakeBtn').querySelector('span').textContent='保持屏幕常亮'}else{wakeLock=await navigator.wakeLock.request('screen');$('wakeBtn').querySelector('span').textContent='已保持常亮'}}else alert('你的浏览器暂不支持屏幕常亮。')}catch(e){console.log(e)}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();deferredInstall=null};window.addEventListener('pagehide',()=>{if(running)stop()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&wakeLock===null&&running&&'wakeLock'in navigator)navigator.wakeLock.request('screen').then(w=>wakeLock=w).catch(()=>{})});restore();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});